@host = http://localhost:5050

GET http://localhost:5290/api/User
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImV4cCI6MTc2MDE4NzM5M30.dMZCm-Msu65UhmP26eu3c_FetQD22fv4QsvDUckql6Y